#cloud-config
package_update: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - containerd

write_files:
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

runcmd:
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  - modprobe overlay
  - modprobe br_netfilter
  - sysctl --system

  - mkdir -p /etc/containerd
  - containerd config default | tee /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd

  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubelet=1.29.6-1.1 kubeadm=1.29.6-1.1
  - apt-mark hold kubelet kubeadm

  - crictl config runtime-endpoint unix:///var/run/containerd/containerd.sock

  - |
    echo "[Cloud-Init] Starte Join-Loop" > /var/log/worker-join.log
    for i in $(seq 1 30); do
      echo "[$(date)] Versuch $i: Lade join.sh vom Master..." >> /var/log/worker-join.log
      if curl -sSf http://10.0.0.2:8080/join.sh -o /tmp/join.sh; then
        echo "[$(date)] join.sh erfolgreich geladen!" >> /var/log/worker-join.log
        chmod +x /tmp/join.sh
        /tmp/join.sh >> /var/log/worker-join.log 2>&1
        exit 0
      fi
      sleep 5
    done
    echo "[$(date)] FEHLER: /tmp/join.sh konnte nicht geladen werden!" >> /var/log/worker-join.log
